# Generated by Django 5.1.7 on 2025-04-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_head_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file_image',
            field=models.ImageField(blank=True, upload_to='blog/files/%Y/%m/%d/'),
        ),
    ]
