# Generated by Django 5.1.7 on 2025-04-29 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_file_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='file_image',
            new_name='file_upload',
        ),
    ]
